# This is a basic workflow to help you get started with Actions

name: KohaDocker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            # Runs a set of commands using the runners shell
            
      - name: Run a multi-line script
        run: |
          wget -O- https://debian.koha-community.org/koha/gpg.asc | sudo apt-key add -
          echo deb http://debian.koha-community.org/koha stable main | sudo tee /etc/apt/sources.list.d/koha.list
          sudo apt update
          sudo apt upgrade
          sudo apt clean
          sudo apt install koha-common
          sudo apt install apache2
          sudo a2enmod rewrite 
          sudo a2enmod cgi 
          sudo systemctl restart apache2.service
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: him2him2/koha-library:latest


